### ISSUE TITLE
Sending dcr always uses default account

### ISSUE THREAD

**Issue by C-ollins** [raedahgroup/dcrios#214]
Sending dcr doesn't make use of selected account. Dcr is always sent using default account

**Comment by macsleven** [comment]
this was fixed here
https://github.com/raedahgroup/dcrios/pull/207

**Comment by C-ollins** [comment]
Issue still occurs on latest build. It also happens to send to account drop down.
